### ISSUE TITLE
Does not safely destroy the mutex (pthread_mutex_destroy can get called while in pthread_cond_wait)

### ISSUE THREAD

**Issue by OneWorld123** [vichargrave/wqueue#2]
Hi Vic, first of all thanks for sharing your code! It was just the missing peace to solve issues in my project!

Unfortunatly your code does not safely destroy the mutex. The [documentation ](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_destroy.html) says:

> It shall be safe to destroy an initialized mutex that is unlocked. Attempting to destroy a locked mutex, or a mutex that another thread is attempting to lock, or a mutex that is being used in a pthread_cond_timedwait() or pthread_cond_wait() call by another thread, results in undefined behavior.

Thats exactly what happens sometimes ;( 

In my case `~wqueue()` gets called from another thread while your `wqueue::remove()` method just executes pthread_cond_wait. However, `pthread_mutex_destroy(&m_mutex)` should never get called at this time.  `pthread_cond_wait` checks at the beginning for destroyed mutex. That's why it doesn't always crash, but sometimes the destroy happens after that check ;(

To reproduce I open and immediately close the dialog that initializes and destroys the thread very often.

To safely destroy the thread probably requires a design change.

In Java I solved that problem with a work item that stops the thread. Maybe that would not require a vast design change.

**Comment by vichargrave** [comment]
The wqueue destructor should not be called from any of your threads.  If any of your threads are trying to do this it is a mistake in your code.

If you look at my examples, in particular the one in Multithreaded Work Queue Based Server in C++, you'll see that the wqueue is created in the main() function and a reference is passed to each of the threads, none of which destroy the wqueue.  The wqueue is destroyed only when the program terminates.

If you want to post your code, I'm happy to take a look at it.

**Comment by OneWorld123** [comment]
I've looked into your [example](https://vichargrave.github.io/articles/2013-03/multithreaded-work-queue-based-server-in-cpp). 

My setting is similiar to yours. I have a producer thread - which is the UI thread of a MFC application that creates and starts the worker thread assigned to one queue. I use your thread and queue implementation.

The worker threads are pointers and the queue is created on stack. Just like your example.

I use the queue to support an autosuggest text box. Each keystroke triggers a query in form of a work item. So, I only need the thread and queue in a single dialog. The constructor of the dialog starts the threads and the deconstructor deletes the thread pointer. The queue (heap variable) is destroyed also after the deconstructor.

I create and destroy the threading mechanism each time the dialog is opened and closed. That's the difference to your code. In fact, I don't see that you deleting the pointers to the worker threads (of type `ConnectionHandler` in your example). I guess you don't care since the program terminates at that point. However, I have to delete those resources properly. 

So, the producer thread should destroy the work queue? 

When the work queue is destroyed very rapidly after construction, I get crashes. The stacktrace then shows that the deconstructor of the work queue was called while code inside `pthread_cond_wait` is being executed. So, the deconstructor of the work queue should wait with destroying the `mutex `and `cond` field until the mutex isn't locked anymore. Additionally, the methods of the queue class should not use those resources anymore when they got destroyed.

**Comment by vichargrave** [comment]
The fact that you see the `pthread_cond_wait` in your stack trace means that you have one or more threads calling wqueue::remove() when the queue is empty, so they are waiting to receive work from the producer thread.  

Your producer-consumer usage is different than the example I provided.  In my example, the application is a server so, the producer and consumer threads live as long as the server is running.  In your case the producer and consumer threads are short lived, so I would suggest the producer send a work item to each worker thread that tells it to quit and not go back to get more work items.  The producer thread would then wait until the queue is empty, then delete each worker thread object (which means the producer would have to keep track of your thread object pointers so it could call delete() on each one of them).  When all worker threads are destroyed and the queue is empty, then and only then, you are able to safely delete the wqueue object and finally exit the producer thread, which itself must be destroyed somehow by the code that created it. 

BTW, my multithread server example *does* delete work items.  It is done in line 69 of server.cpp which in turn deletes the TCPStream objects so the connections are closed.  The worker threads are not deleted because the example is a multithreaded server, so the worker threads are supposed to hang around to handle more work when new connections arrive.

I'm going to close this this issue.

**Comment by OneWorld123** [comment]
Your first paragraph of your last comment helped me to to find the cause. 

Your recommendation how to implement deleting the resources is good, but I rather chose that way:

Now, I add a work item to the queue the worker thread recognizes as signal to break the for-loop and to delete itself. When that work item is being executed it also deletes a pointer to the work queue. Not the most elegant solution, but it works to delete the pointers in the right moment.  (e.g. it works only correct if one thread is assigned to the queue)

I never said you don't delete work items. 

By the way, you could mention in your docs, that your queue implementation is similiar to Android API's [Handler](https://developer.android.com/reference/android/os/Handler.html) (if only one worker thread powers the queue). I use it as that. My work items all derive from a pure virtual class called `Runnable` with the single method `run()`. Similiar to JAVA's [Runnable](https://developer.android.com/reference/java/lang/Runnable.html)
